name: Deepali ML Proj2

on:
  push:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
         path: |
          ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/*.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt #installing requirements
      
      - name: Build Docker image 
        run: docker build . -t deepali1409/deepali_proj2_dockerrepo:latest
      - name: publish
        run: docker login -u deepali1409 -p ${{ secrets.DOCKER_HUB_TOKEN }}
             docker push deepali1409/deepali_proj2_dockerrepo:latest
        # with:
        #   context: .
        #   push: true
        #   tags: deepali1409/deepali_proj2_dockerrepo:latest
        #   registry: docker.io
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_PASSWORD }}